package com.tcu.projectpulse.war.domain;

public enum ActivityCategory {
    DEVELOPMENT, TESTING, BUGFIX, COMMUNICATION, DOCUMENTATION,
    DESIGN, PLANNING, LEARNING, DEPLOYMENT, SUPPORT, MISCELLANEOUS
}